name: Daily ETL Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall -r requirements.txt
        pip check
        
    - name: Verify installation
      run: |
        python -c "import numpy; print(f'numpy: {numpy.__version__}')"
        python -c "import pandas; print(f'pandas: {pandas.__version__}')"

    - name: Run Tests
      run: |
        python -m pytest Tests/ -v

    - name: Run ETL
      run: |
        python -c "from extract import fetch_data; from transform import transform_data; from load import save_to_csv; data = fetch_data('https://jsonplaceholder.typicode.com/posts'); transformed = transform_data(data); save_to_csv(transformed)"
        
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: etl-output
        path: output_*.csv